name: Build and test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: CMake
      run: mkdir build && cd build && cmake -GNinja ..
    - name: Build
      run: cmake --build build
